[flant] picked fixes for vernemq build

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -1,16 +1,15 @@
 SERVICE:= $(notdir $(patsubst %/,%,$(lastword $(CURDIR))))
 TAG:=$$(git tag | sort -r -V | head -1)
 
-
-
 .SILENT:
 .PHONY: help
 
-REG_HOST="netologygroup"
+REG_HOST="foxford"
 
 build:
-	docker build --rm -t $(REG_HOST)/${SERVICE}:${TAG} --no-cache . 
-	docker push $(REG_HOST)/${SERVICE}
+	if [[ ! "${TAG}" ]]; then echo "TAG is required." 1>&2; exit 1; fi
+	docker build --rm -t ${REG_HOST}/${SERVICE}:${TAG} --no-cache . 
+	docker push $(REG_HOST)/${SERVICE}:${TAG}
 
 help:
         echo "help:"
